name: CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build project (Release)
        run: msbuild DH.IME.SpotSol\workspace\DH.IME.Spot\DH.IME.Spot.csproj /restore /t:Build /p:Configuration=Release /v:minimal
